!-------------------------------------------------------------------------------
! ROFI color theme
!-------------------------------------------------------------------------------
! File: gruvbox-dark.theme
! Desc: Gruvbox dark color theme for rofi
! Author: bardisty <b@bah.im>
! Source: https://github.com/bardisty/gruvbox-rofi
! Modified: Fri Sep 23 2016 01:50:52 PDT -0700
!-------------------------------------------------------------------------------
! Based on the Gruvbox color scheme for Vim by morhetz
! https://github.com/morhetz/gruvbox
!-------------------------------------------------------------------------------

! Enable the extended coloring options
rofi.color-enabled: true

!                  bg       border   separator
rofi.color-window: #282828, #a89984, #a89984

!                  bg       fg       bg-alt   hl-bg    hl-fg
rofi.color-normal: #282828, #ebdbb2, #32302f, #665c54, #fbf1c7
rofi.color-active: #d79921, #282828, #d79921, #fabd2f, #282828
rofi.color-urgent: #cc241d, #282828, #cc241d, #fb4934, #282828
