!-------------------------------------------------------------------------------
! ROFI color theme
!-------------------------------------------------------------------------------
! File: gruvbox-light.theme
! Desc: Gruvbox light color theme for rofi
! Author: bardisty <b@bah.im>
! Source: https://github.com/bardisty/gruvbox-rofi
! Modified: Fri Sep 23 2016 01:50:59 PDT -0700
!-------------------------------------------------------------------------------
! Based on the Gruvbox color scheme for Vim by morhetz
! https://github.com/morhetz/gruvbox
!-------------------------------------------------------------------------------

! Enable the extended coloring options
rofi.color-enabled: true

!                  bg       border   separator
rofi.color-window: #fbf1c7, #7c6f64, #7c6f64

!                  bg       fg       bg-alt   hl-bg    hl-fg
rofi.color-normal: #fbf1c7, #3c3836, #f2e5bc, #7c6f64, #fdf4c1
rofi.color-active: #b57614, #fdf4c1, #b57614, #d79921, #fdf4c1
rofi.color-urgent: #cc241d, #fdf4c1, #cc241d, #fb4934, #fdf4c1
